Kleshenko Anna || HW4 done
kleshenkoaa/task-tracker pull request #2
Opened 2021-04-29 18:19 UTC by kleshenkoaa

Появилась проблема с тем, что в браузере отображалась старая страничка из кэша, пробовала чистить, не помогло - пришлось делать новое приложение и переносить из него код сюда.

2021-05-08 10:47 UTC, ValeryStatinov requested changes

2021-05-08 10:47 UTC, ValeryStatinov commented on src/components/List/List.js
> +        this.lastId += 1
`lastId` - непроинициальзированное поле

2021-05-08 10:47 UTC, ValeryStatinov commented on src/components/Item/Item.js
> +                        }
nope:( это приводит к рассинхрону данные. в массие в стейте у этой таски будет значение status одно, а здесь уже, возможно, другое

а если вдруг массив тасок использовался бы где-то еще в приложении, то как понять, какое значение статуса использовать: отсюда или из массива?

2021-05-08 10:47 UTC, ValeryStatinov commented on src/components/Item/Item.js
> +                        }
при клике на кнопку значение статуса должно меняться в массиве в стейте

2021-05-11 20:09 UTC, kleshenkoaa commented on src/components/Item/Item.js
> +                        }
Исправила

2021-05-12 09:28 UTC, ValeryStatinov approved these changes
теперь хорошо:) отл(9)

2021-05-12 09:28 UTC, ValeryStatinov commented on .vscode/launch.json
> +}
.vscode в гитигнор в след дз и удалить из репозитория

2021-05-12 09:28 UTC, merged