Hw  6
kleshenkoaa/task-tracker pull request #4
Opened 2021-05-30 13:32 UTC by kleshenkoaa

HW-6 done

2021-06-19 20:18 UTC, ValeryStatinov requested changes

2021-06-19 20:18 UTC, ValeryStatinov commented on src/App.js
> +                </Route>
id проекта должен быть динамическим

2021-06-19 20:18 UTC, ValeryStatinov commented on src/components/List/1
> + addTask = ({name, description}) => {
что за расширение у файла

2021-06-19 20:19 UTC, ValeryStatinov commented
либо могу зачесть такое с оценкой хор(5)

2021-06-20 20:13 UTC, kleshenkoaa commented
> либо могу зачесть такое с оценкой хор(5)

Надо только динамический Id поправить? Второй файл это черновик, его удалю

5 это удовл :с

2021-06-20 21:40 UTC, kleshenkoaa commented on src/App.js
> +                </Route>
Исправила

2021-06-20 21:40 UTC, kleshenkoaa commented
Поправила id, удалила ненужный файл

2021-06-22 10:17 UTC, ValeryStatinov approved these changes
отл(8)

2021-06-22 10:17 UTC, merged